#!/bin/bash
#
# generate a new, random ssh password

function generate () {

    local LEN=$1
    [ "$LEN" == "" ] && LEN=20
    tr -dc A-Za-z0-9_ < /dev/urandom | head -c ${LEN} | xargs
}

generate $1
