#!/bin/bash
#
# This script is intened for use with easily viewing processes
#
# author: jupiter
# version: 1.1
# edit: 2013/07/12
#

function showHelp () {
	echo "$0 usage:"
	echo "	<regex> 	Regular expression to search for."
	echo
}

if [ $1 == "-h" ] || [ $1 == "--help" ] ; then
	showHelp
else
	ps -ef | grep "$1"
fi
