#!/bin/bash
# This script finds all running processes that have the 
# imput regular expression
#
# Author: jupiter
# Version 1.2

function showHelp () {
	echo "$0 usage:"
	echo "	<regex> 	Regular expression to search for."
	echo
}

if [ $1 == "-h" ] || [ $1 == "--help" ] ; then
	showHelp
else
	ps -ef | grep "$1"
fi
